import requests
from os import path

URL = 'https://stev.oapd.inaf.it/cgi-bin/trilegal/trilegal_1.6'

query = {
    'gal_coord': '1',
    'gc_l': '0',
    'gc_b': '0',
    'eq_alpha':  '0',
    'eq_delta': '0',
    'field':  '0.001',
    'photsys_file': 'tab_mag_odfnew/tab_mag_Roman2021.dat',
    'icm_lim': '4',
    'mag_lim': '30',
    'mag_res': '0.1',
    'imf_file': 'tab_imf/imf_chabrier_lognormal.dat',
    'binary_kind': '1',
    'binary_frac': '0.3',
    'binary_mrinf': '0.7',
    'binary_mrsup': '1',
    'output_printbinaries': '0',
    'extinction_kind': '2',
    'extinction_h_z': '110',
    'extinction_h_r': '100000',
    'extinction_kind': '1',
    'extinction_rho_sun': '0.00015',
    'extinction_infty': '0.0378',
    'extinction_sigma': '0',
    'r_sun': '8700',
    'z_sun': '24.2',
    'thindisk_kind': '0',
    'thindisk_kind': '1',
    'thindisk_kind': '3',
    'thindisk_h_z0': '94.6902',
    'thindisk_hz_tau0': '5.55079e9',
    'thindisk_hz_alpha': '1.6666',
    'thindisk_h_r': '2913.36',
    'thindisk_r_min': '0',
    'thindisk_r_max': '15000',
    'thindisk_rho_sun': '55.4082',
    'thindisk_file': 'tab_sfr/file_sfr_thindisk_mod.dat',
    'thindisk_a': '0.735097',
    'thindisk_b': '0',
    'thickdisk_kind': '3',
    'thickdisk_h_z': '800',
    'thickdisk_h_r': '2394.07',
    'thickdisk_r_min': '0',
    'thickdisk_r_max': '15000',
    'thickdisk_rho_sun': '0.0010',
    'thickdisk_file': 'tab_sfr/file_sfr_thickdisk.dat',
    'thickdisk_a': '1',
    'thickdisk_b': '0',
    'halo_kind': '2',
    'halo_r_eff': '2698.93',
    'halo_q': '0.583063',
    'halo_rho_sun': '0.000100397',
    'halo_file': 'tab_sfr/file_sfr_halo.dat',
    'halo_a': '1',
    'halo_b': '0',
    'bulge_kind': '2',
    'bulge_am': '2500',
    'bulge_a0': '95',
    'bulge_eta': '0.68',
    'bulge_csi': '0.31',
    'bulge_phi0': '15',
    'bulge_rho_central': '406.0',
    'bulge_file': 'tab_sfr/file_sfr_bulge_zoccali_p03.dat',
    'bulge_a': '1',
    'bulge_b': '-2.0e9',
    'object_kind': '0',
    'object_mass': '1280',
    'object_dist': '1658',
    'object_av': '1.504',
    'object_avkind': '1',
    'object_file': 'tab_sfr/file_sfr_m4.dat',
    'object_a': '1',
    'object_b': '0',
    'output_kind': '1',
    'object_kind': '0',
    'bulge_cutoffmass': '0.01',
    'object_cutoffmass': '0.8',
   # 'hidden_fields': '.cgifields=binary_kind?.cgifields=bulge_kind?.cgifields=extinction_kind?.cgifields="gal_coord"?.cgifields=halo_kind?.cgifields="output_printbinaries"?.cgifields="thickdisk_kind"?.cgifields="thindisk_kind"'
}

#query_string = path.join(URL, params=query)

response = requests.get(URL, params=query)
print(response.text)
